# Generated by Django 6.0 on 2025-12-19 16:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='NIT Emisor')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número Factura')),
                ('subtotal_factura', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('ic', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IC')),
                ('inc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INC')),
                ('ica', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICA')),
                ('rete_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención Fuente')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha Recepción')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('total_retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Retenciones')),
                ('total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Factura')),
                ('tipo_cliente', models.CharField(max_length=50, verbose_name='Tipo Cliente')),
                ('periodo_factura', models.CharField(max_length=50, verbose_name='Período Factura')),
                ('notas_finales', models.TextField(blank=True, verbose_name='Notas Finales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número Nota')),
                ('tipo', models.CharField(choices=[('credito', 'Nota Crédito'), ('debito', 'Nota Débito')], max_length=10, verbose_name='Tipo Nota')),
                ('tipo_operacion', models.CharField(max_length=10, verbose_name='Tipo Operación')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('hora_emision', models.TimeField(verbose_name='Hora Emisión')),
                ('factura_referencia', models.CharField(max_length=50, verbose_name='Factura Referencia')),
                ('codigo_concepto', models.CharField(max_length=10, verbose_name='Código Concepto')),
                ('descripcion_concepto', models.TextField(verbose_name='Descripción Concepto')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Base')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IVA')),
                ('retencion_renta', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retención Renta')),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Retención')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('cufe', models.CharField(blank=True, max_length=255, verbose_name='CUFE')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='generado', max_length=20, verbose_name='Estado')),
                ('nit_emisor', models.CharField(max_length=20, verbose_name='NIT Emisor')),
                ('razon_social_emisor', models.CharField(max_length=255, verbose_name='Razón Social Emisor')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Bruto')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Crédito/Débito',
                'verbose_name_plural': 'Notas Crédito/Débito',
                'db_table': 'notas_credito_debito',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
    ]
